[project]
name = "projet04"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy>=2.2.5",
    "pyinstrument>=5.0.1",
    "pytest>=8.3.5",
    "scipy>=1.15.2",
]

[dependency-groups]
dev = [
    "pytest-cov>=6.1.1",
]
